# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/chagalllte/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/chagalllte

PRODUCT_COPY_FILES += \
    vendor/samsung/chagalllte/proprietary/vendor/lib/hw/consumerir.universal5420.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/consumerir.universal5420.so \
    vendor/samsung/chagalllte/proprietary/system/bin/gps.cer:/system/bin/gps.cer \
    vendor/samsung/chagalllte/proprietary/vendor/bin/cbd:$(TARGET_COPY_OUT_VENDOR)/bin/cbd \
    vendor/samsung/chagalllte/proprietary/vendor/bin/gpsd:$(TARGET_COPY_OUT_VENDOR)/bin/gpsd \
    vendor/samsung/chagalllte/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/chagalllte/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/chagalllte/proprietary/vendor/etc/plmn_se13.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13.bin \
    vendor/samsung/chagalllte/proprietary/vendor/lib/hw/gps.universal5420.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.universal5420.so \
    vendor/samsung/chagalllte/proprietary/vendor/lib/sensors.universal5420.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.universal5420.so \
    vendor/samsung/chagalllte/proprietary/vendor/lib/libfloatingfeature.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfloatingfeature.so \
    vendor/samsung/chagalllte/proprietary/vendor/lib/libprotobuf-cpp-haxx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libprotobuf-cpp-haxx.so \
    vendor/samsung/chagalllte/proprietary/vendor/lib/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril.so \
    vendor/samsung/chagalllte/proprietary/vendor/lib/libwrappergps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwrappergps.so 
   
PRODUCT_COPY_FILES += \
    $(foreach f,$(wildcard vendor/samsung/chagalllte/proprietary/vendor/etc/nxp_note4/*.txt),$(f):$(TARGET_COPY_OUT_VENDOR)/etc/nxp/$(notdir $(f)))
    
PRODUCT_COPY_FILES += \
    $(foreach f,$(wildcard vendor/samsung/chagalllte/proprietary/vendor/etc/nxp_note4/BargeIn/*.txt),$(f):$(TARGET_COPY_OUT_VENDOR)/etc/nxp/BargeIn/$(notdir $(f)))
PRODUCT_COPY_FILES += \
    $(foreach f,$(wildcard vendor/samsung/chagalllte/proprietary/vendor/etc/nxp_note4/BargeInDriving/*.txt),$(f):$(TARGET_COPY_OUT_VENDOR)/etc/nxp/BargeInDriving/$(notdir $(f)))
PRODUCT_COPY_FILES += \
    $(foreach f,$(wildcard vendor/samsung/chagalllte/proprietary/vendor/etc/nxp_note4/mVoIP/*.txt),$(f):$(TARGET_COPY_OUT_VENDOR)/etc/nxp/mVoIP/$(notdir $(f)))
PRODUCT_COPY_FILES += \
    $(foreach f,$(wildcard vendor/samsung/chagalllte/proprietary/vendor/etc/nxp_note4/mVoIPFMC/*.txt),$(f):$(TARGET_COPY_OUT_VENDOR)/etc/nxp/mVoIPFMC/$(notdir $(f)))
PRODUCT_COPY_FILES += \
    $(foreach f,$(wildcard vendor/samsung/chagalllte/proprietary/vendor/etc/nxp_note4/mVoIPSec/*.txt),$(f):$(TARGET_COPY_OUT_VENDOR)/etc/nxp/mVoIPSec/$(notdir $(f)))
PRODUCT_COPY_FILES += \
    $(foreach f,$(wildcard vendor/samsung/chagalllte/proprietary/vendor/etc/nxp_note4/VideoTelephony/*.txt),$(f):$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VideoTelephony/$(notdir $(f)))